### ISSUE TITLE
Improved resizing to preserve flux and centring

### ISSUE THREAD

**Issue by bamford** [astroferreira/areia#1]
I used AREIA as the starting point for an undergrad project, but we identified some issues with flux conservation (which you fixed in c3ceb3), needing to pad to retain the image size, and the centre of the galaxy moving (which I think is somewhat related to f1a7b8). I addressed these issues in a quite different way, which you may be interested in considering. See https://github.com/aidenrolfe/ARG/blob/main/redshifting.py and the tests in [this notebook](https://gist.github.com/bamford/4ccc4da519bba5216f58d12070865fc3). Note that I also sped things up by operating on a whole stack of images simultaneously, but then one can run into memory issues, so I process the images in batches.

**Comment by astroferreira** [comment]
Hi @bamford,

Thanks for this, I will have a look. Dealing with the rebinning in a different way than just using scipy zoom is in my backlog for quite some time now, but I never got around on doing it. 

This can also be important for the rebinning when making the outputs the proper size for the networks.

**Comment by astroferreira** [comment]
Hey @bamford,

I finally touched AREIA again after a long time. I included the zoom_contents function and enabled it via a config option:

If `cfg.fixed_grid=True`, then it uses zoom_contents, otherwise it fallsback to the original implementation. I will do some more tests before making it default, but it worked great right out off the bat.

Thanks for the suggestion
